openapi: 3.0.0
info:
  title: Task API
  description: API for creating, updating, and deleting tasks
  version: 1.0.0
paths:
  /tasks:
    get:
      summary: List tasks with keyset pagination
      operationId: listTasks
      parameters:
        - name: limit
          in: query
          required: false
          description: Maximum number of tasks to return
          schema:
            type: integer
        - name: cursor
          in: query
          required: false
          description: Cursor (ID of the last task from the previous page)
          schema:
            type: string
      responses:
        "200":
          description: A list of tasks and the next cursor
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: "#/components/schemas/Task"
                  nextCursor:
                    type: string
                    description: Cursor for the next page of tasks
    post:
      summary: Create a new task
      operationId: createTask
      requestBody:
        description: Task object to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created successfully
    put:
      summary: Update an existing task
      operationId: updateTask
      requestBody:
        description: Task object to update
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "200":
          description: Task updated successfully
  /tasks/{id}:
    get:
      summary: Get a task by ID
      operationId: getTask
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: string
      responses:
        "200":
          description: The task with the given ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found
    delete:
      summary: Delete a task
      operationId: deleteTask
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Task ID to delete
      responses:
        "204":
          description: Task deleted successfully

components:
  schemas:
    Task:
      type: object
      properties:
        title:
          type: string
        status:
          type: string
          enum: [complete, incomplete, in-progress]
        content:
          type: string
