version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: test_password
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/tasklist
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - DB_URI=mongodb://mongo:27017
      - DB_USER=test_user
      - DB_PASSWORD=test_password
      - DB_NAME=testdb
    networks:
      - app-network

volumes:
  mongo_data:
    driver: local
networks:
  app-network:
    driver: bridge
