run:
  build-tags:
    - integration

linters-settings:
  goimports:
    local-prefixes: github.com/hizagi/fullstack-challenge-jobsity/backend

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - golint
    - unused
    - ineffassign
    - gocyclo
    - bodyclose
    - unparam